
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation ui: !include automations.yaml
#automation manual: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: 114 Priory Park
  unit_system: metric
  currency: GBP
  longitude: !secret home_longitude #54.33372
  latitude: !secret home_latitude # 5.58304

zone:
  - name: Home_new
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 75
    icon: mdi:home
